[tool.poetry]
name = "beebop"
version = "0.1.0"
description = "Python API for beebop"
authors = ["muppi1993 <clara.gronemeyer20@imperial.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
