# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python unit & integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with: 
        path: main
    - name: Download and extract GPS database
      working-directory: ./main/storage
      run: |
        wget https://sketchdb.blob.core.windows.net/public-dbs/GPS_v4_full.tar.bz2
        tar -xf GPS_v4_full.tar.bz2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.9
        activate-environment: beebop_py
        channels: bioconda, conda-forge
    - name: activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
#    - name: Install poppunk
#      run: conda install poppunk
# currently the latest poppunk release is missing some functions required for beebop. For now installing from source:
    - name: Get poppunk source code
      uses: actions/checkout@v3
      with:
        repository:  bacpop/PopPUNK 
        path: poppunk
    - name: install poppunk & dependencies
      working-directory: ./poppunk
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        conda install pybind11
        conda install pp-sketchlib
        conda install dendropy
        conda install hdbscan
        conda install matplotlib
        conda install graph-tool
        conda install pandas
        conda install sharedmem
        conda install cmake
        conda install tqdm
        conda install networkx
        conda install flask_cors
        conda install flask-apscheduler
        sudo apt-get install libeigen3-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install -y libxcb-icccm4
        sudo apt-get install -y libxcb-image0
        sudo apt-get install -y libxcb-keysyms1
        sudo apt-get install -y libxcb-render-util0
        conda install requests
        conda install -c conda-forge pp-sketchlib=1.7
        sed -i -z 's/sketch_dict = json.loads(top_value)/if type(top_value) == str:\n            sketch_dict = json.loads(top_value)\n        else:\n            sketch_dict = top_value/' PopPUNK/web.py
        python setup.py install
        python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        poetry install
        conda install pytest-xvfb
    - name: Use Node.js for pm2
      uses: actions/setup-node@v2
    - name: Run Redis & rqworker and test with pytest
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        ./scripts/start_redis
        export PATH="/usr/share/miniconda/bin:$PATH"
        TESTING=True poetry run pytest
    - name: tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
