# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python unit & integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with: 
        path: main

    - name: Download and extract GPS database
      working-directory: ./main
      run: |
        ./scripts/download_db --small storage
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        python-version: 3.9
        activate-environment: beebop_py
        channels: bioconda, conda-forge

    - name: activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py

#    - name: Install poppunk
#      run: conda install poppunk
# currently the latest poppunk release is missing some functions required for beebop. For now installing from source:

    - name: Get poppunk source code
      uses: actions/checkout@v3
      with:
        repository:  bacpop/PopPUNK 
        ref: fix-json-serialisation
        path: poppunk

    - name: install poppunk & dependencies
      working-directory: ./poppunk
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        conda install pybind11
        conda install pp-sketchlib
        conda install dendropy
        conda install scikit-learn=1.0.2
        conda install hdbscan
        conda install matplotlib
        conda install graph-tool
        conda install pandas
        conda install sharedmem
        conda install cmake
        conda install tqdm
        conda install networkx
        conda install flask_cors
        conda install flask-apscheduler
        sudo apt-get install libeigen3-dev
        sudo apt-get install libopenblas-dev
        sudo apt-get install -y libxcb-icccm4
        sudo apt-get install -y libxcb-image0
        sudo apt-get install -y libxcb-keysyms1
        sudo apt-get install -y libxcb-render-util0
        conda install requests
        conda install -c conda-forge pp-sketchlib=1.7
        python setup.py install
        python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

    - name: Get rapidnj source code
      uses: actions/checkout@v3
      with:
        repository:  somme89/rapidNJ 
        path: rapidnj

    - name: Install rapidnj
      working-directory: ./rapidnj
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        make
        cd bin
        mv rapidnj /usr/share/miniconda/bin

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    - name: Install dependencies
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        poetry install
        conda install pytest-xvfb

    - name: Run Redis
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        docker pull redis
        docker run --rm -d --name=redis -p 6379:6379 redis

    - name: Test with pytest
      env:
        MICROREACT_TOKEN: ${{ secrets.MICROREACT_TOKEN }}
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        export PATH="/usr/share/miniconda/bin:$PATH"
        rqworker > rq_output.txt 2>&1 &
        STORAGE_LOCATION=./tests/results DB_LOCATION=./storage/GPS_v4_references poetry run coverage run -m pytest

    - name: Process coverage
      working-directory: ./main
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
        export PATH="/usr/share/miniconda/bin:$PATH"
        poetry run coverage report -m && poetry run coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        root_dir: ./main

    # Uncomment the next three lines to debug on failure with
    # tmate. However, don't leave them uncommented on merge as that
    # causes failing builds to hang forever.
    #
    # - name: tmate session
    #   if: ${{ failure() }}
    #   uses: mxschmitt/action-tmate@v3
