name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: beebop_py
    - name: Install poppunk
      run: |
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install poppunk
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install
    - name: Use Node.js for pm2
      uses: actions/setup-node@v2
    - name: Run Redis & rqworker
      working-directory: .
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        ./scripts/start_redis 
    - name: Test with pytest
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        poetry run pytest
    - name: Stop redis
      working-directory: .
      run: ./scripts/stop_redis
