# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
      with: 
        path: main
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: beebop_py
        channels: bioconda, conda-forge
    - name: activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
#    - name: Install poppunk
#      run: conda install poppunk
# currently the latest poppunk release is missing some functions required for beebop. For now installing from source:
    - name: Install poppunk from source
      uses: actions/checkout@v3
      with:
        repository:  bacpop/PopPUNK 
        path: poppunk
    - name: activate environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate beebop_py
    - name: install poppunk & dependencies
      working-directory: ./poppunk
      run: |
        conda install pybind11
        conda install pp-sketchlib
        conda install dendropy
        conda install hdbscan
        conda install matplotlib
        conda install graph-tool
        conda install pandas
        conda install sharedmem
        conda install cmake
        conda install tqdm
        conda install networkx
        conda install pytest
        conda install flask_cors
        conda install flask-apscheduler
        sudo apt-get install libeigen3-dev
        python setup.py install
        python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      working-directory: ./main
      run: poetry install
    - name: Use Node.js for pm2
      uses: actions/setup-node@v2
    - name: Run Redis & rqworker
      working-directory: ./main
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        ./scripts/start_redis
    - name: tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Test with pytest
      working-directory: ./main
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        poetry run pytest
