# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: beebop_py
    - name: install poppunk & poetry
      run: |
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install poppunk
        conda install poetry
    - name: Install dependencies
      run: poetry install
    - name: Use Node.js for pm2
      uses: actions/setup-node@v2
    - name: Run Redis & rqworker
      working-directory: .
      run: ./scripts/start_redis 
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Stop redis
      working-directory: .
      run: ./scripts/stop_redis
